blog/urls.py
from django.urls import path
from . import views

app_name = 'blogs'

urlpatterns = [
    path('', views.homepage, name='homepage'),
    path('categories/<category_slug>', views.category, name='category'),
    path('blog/<blog_slug>', views.blog, name='blog'),
    path('search',views.search, name='search')
]

blogproject1/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls'))
]

blog/models.py
from django.db import models
from ckeditor.fields import RichTextField


# Create your models here.

class Category(models.Model):
    title = models.CharField(max_length=20)
    slug = models.CharField(max_length=50, unique=True, null=False)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural = "categories"


class Blog(models.Model):
    title = models.CharField(max_length=255)
    slug = models.CharField(max_length=50, unique=True, null=False)
    content = RichTextField()
    pub_date = models.DateTimeField()
    category = models.ForeignKey(Category, on_delete=models.CASCADE)

    def __str__(self):
        return self.title


class Comment(models.Model):
    name = models.CharField(max_length=150)
    email = models.EmailField()
    message = models.TextField()
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE)

blog/forms.py
from django.forms import ModelForm
from .models import Comment


class CommentForm(ModelForm):
    class Meta:
        model = Comment
        # fields= '__all__'
        exclude = ['blog']

blog/views.py
from django.shortcuts import render, redirect
from .models import Category, Blog
from .forms import CommentForm
from django.views import generic


# Create your views here.

def homepage(request):
    context = {
        'categories': Category.objects.order_by('title'),
        'blogs': Blog.objects.order_by('pub_date')[:5]
    }
    return render(request, 'index.html', context)


def category(request, category_slug):
    cat = Category.objects.get(slug=category_slug)
    print(cat)
    context = {'categories': Category.objects.order_by('title'),
               'blogs': cat.blog_set.order_by('-pub_date'),
               'category': cat
               }

    return render(request, 'category.html', context)


def blog(request, blog_slug):
    blg = Blog.objects.get(slug=blog_slug)

    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.blog = blg
            comment.save()
            form = CommentForm()
    else:
        form = CommentForm()
    context = {
        'categories': Category.objects.order_by('title'),
        'form': form,
        'blog': blg
    }
    return render(request, 'blog.html', context)


def search(request):
    if request.GET.get('q'):
        context = {
            'categories': Category.objects.order_by('title'),
            'blogs': Blog.objects.filter(title__icontains=request.GET.get('q'))
        }
        return render(request, 'search.html', context)

    return redirect('/')

blog/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>My Blogs</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <style>
        /* Set height of the grid so .sidenav can be 100% (adjust if needed) */
        .row.content {
            height: 1500px
        }

        /* Set gray background color and 100% height */
        .sidenav {
            background-color: #f1f1f1;
            height: 100%;
        }

        /* Set black background color, white text and some padding */
        footer {
            background-color: #555;
            color: white;
            padding: 15px;
        }

        /* On small screens, set height to 'auto' for sidenav and grid */
        @media screen and (max-width: 767px) {
            .sidenav {
                height: auto;
                padding: 15px;
            }

            .row.content {
                height: auto;
            }
        }
    </style>
</head>
<body>

<div class="container-fluid">
    <div class="row content">
        <div class="col-sm-3 sidenav">
            <h4><a href="/"> Suman's Blog </a></h4>
            <ul class="nav nav-pills nav-stacked">
                {% for cat in categories %}
                    <li class="{% if cat == category %}
                        active
                    {% endif %}"><a href="{% url 'blogs:category' cat.slug %}">{{ cat.title }}</a></li>
                {% endfor %}
            </ul>
            <br>
            <form action="{% url 'blogs:search' %}" method="GET">
                <div class="input-group">
                    <input name="q" type="text" class="form-control" placeholder="Search Blog..">
                    <span class="input-group-btn">
          <button class="btn btn-default" type="submit">
            <span class="glyphicon glyphicon-search"></span>
          </button>
        </span>
                </div>

            </form>
        </div>

        <div class="col-sm-9">
            {% block content %}  {% endblock %}
        </div>
    </div>
</div>

<footer class="container-fluid">
    <p>Footer Text</p>
</footer>

</body>
</html>

blog/templates/blog.html
{% extends 'base.html' %}

{% load bootstrap3 %}

{% block content %}
    <h1>{{ blog.title }}</h1>
    <div class="well">
        {{ blog.content | safe }}
    </div>
    <div class="panel panel-primary ">
        <div class="panel-heading">
          <span class="badge">{{ blog.comment_set.count }}</span> Comments
        </div>
    </div>
    <div class="panel-body">
        {% for comment in blog.comment_set.all %}
            <div class="row">
                <div class="col-sm-10">
                    <h4>{{ comment.name }}</h4>
                    <p> {{ comment.message }}</p>
                </div>
            </div>
        {% endfor %}
    </div>
    <form action="" method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}
        <button class="btn btn-primary" type="submit">Submit</button>
    </form>
{% endblock %}

blog/templates/category.html
{% extends 'base.html' %}

{% block content %}
    <h4>
        {{ category.title }}
    </h4>

    {% for blog in blogs %}
        <hr>
        <a href="{% url 'blogs:blog' blog.slug %}"><h2>{{ blog.title }}</h2></a>
        <h5><span class="glyphicon glyphicon-time"></span> Post At {{ blog.pub_date }}</h5>
    {% endfor %}

{% endblock %}

blog/templates/index.html
{% extends 'base.html' %}

{% block content %}
    <h4>
        <small>RECENT POSTS</small>
    </h4>
    {% for blog in blogs %}
        <hr>
        <a href="{% url 'blogs:blog' blog.slug %}"><h2>{{ blog.title }}</h2></a>
        <h5><span class="glyphicon glyphicon-time"></span> Post At {{ blog.pub_date }}</h5>
    {% endfor %}

{% endblock %}

blog/templates/search.html
{% extends 'base.html' %}

{% block content %}
    <h4>
        <small>Search Results</small>
    </h4>
    {% for blog in blogs %}
        <hr>
        <a href="{% url 'blogs:blog' blog.slug %}"><h2>{{ blog.title }}</h2></a>
        <h5><span class="glyphicon glyphicon-time"></span> Post At {{ blog.pub_date }}</h5>
    {% endfor %}

{% endblock %}